config/routes.rb
Rails.application.routes.draw do
  resources :zombies do
	  resources :brains
  end

 get '/ZombieCity/cerebros', to: 'brains#index', as:'brains'	  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
	belongs_to :zombie

	validates :flavor, presence: true
	validates :iq, numericality: {only_integer: true, :message => "Solo enteros"}
end

app/models/zombie.rb
class Zombie < ApplicationRecord
	has_many :brains
	mount_uploader :avatar, AvatarUploader

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	

	validates :name, presence: true
	validates :bio, length: {in: 2..100, :message => "Biografía del zombie"}
	validates :age, numericality: {only_integer: true, :message => "Solo enteros"}
	validates :email, format: {:with => VALID_EMAIL_REGEX, message: "Formato de correo inválido"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
    @zombies = Zombie.all
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
    @zombie = Zombie.find(params[:zombie_id]);
    @brain = @zombie.brains.create(brain_params);

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:flavor, :iq, :fresh, :zombie_id)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
    #@zombie.avatar = params[:file]
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :bio, :age, :email, :rotten, :avatar, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_brain.html.erb
<%= div_for brain do%>
	<table>
		<thead>
			<tr>
				<th>Sabor</th>
      			<th>Iq</th>
      			<th>Fresco</th>
      			<th>Agregado hace...</th>
    	  		<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= brain.flavor %></td>
        		<td><%= brain.iq %></td>

        		<td class="Avatar">
        			<% if brain.fresh %>
        				<%= image_tag 'brains/fresh.png',class: 'brains_fresh'%>
        			<% else %>
        				<%= image_tag 'brains/no_fresh.png',class: 'brains_fresh'%>
        			<% end %>
        		</td>
        		<td>
        			<%= time_ago_in_words(brain.created_at)%>
        		</td>
			</tr>
		</tbody>
	</table>
<% end %>

app/views/brains/_form.html.erb
<%= form_with(model: brain, local: true) do |form| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :zombie_id%>  
    <%= f.collection_select :zombie_id,Zombie.order(:name),:id,:name,include_blank:false %>
  </div>
  <div class="field">
    <%= form.label :Sabor %>
    <%= form.text_field :flavor %>
  </div>

  <div>
    <%= form.label :Iq %>
    <%= form.number_field :iq%>
  </div>
  <div>
    <%= form.label :Fresco %>
    <%= form.check_box :fresh %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar cambios" %>
  </div>
<% end %>

app/views/brains/create.js.erb
var new_brain = $("<%= escape_javascript(render(:partial => @brains))%>").hide();
$('#brains').prepend(new_brain);
$('#brain_<%= @brain.id %>').fadeIn('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Mostrar', @brain %> |
<%= link_to 'Atras', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>
<div class="row">
<table>
  <thead>
    <tr>
      <th>Sabor</th>
      <th>IQ</th>
      <th>¿Fresco?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
        <td class="Avatar">
            <%if brain.fresh%>
              <%= image_tag 'brains/fresh.png', class: 'brains_fresh' %>
            <%else%>
              <%= image_tag 'brains/no_fresh.png', class: 'brains_fresh' %>
            <%end%>

        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Atras', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  	<%= @brain.flavor %>
  <strong>Coeficiente intelectual</strong>
	<%= @brain.iq %>
  <strong>¿Está fresco?</strong>  
	<%= @brain.fresh %>
</p>

<div class="Links button round"><%= link_to 'Edit', edit_brain_path(@brain) %> </div>
<div class="Links button round"><%= link_to 'Back', brains_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="js/vendor/jquery.js"></script>
  <script src="js/foundation/foundation.js"></script>
  <script src="js/foundation/foundation.topbar.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Zombie City" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <a href="#" class="button" data-dropdown="drop">Link Dropdown &raquo;</a>
<ul id="drop" class="[tiny small medium large content]f-dropdown" data-dropdown-content>
  <li><a href="#">This is a link</a></li>
  <li><a href="#">This is another</a></li>
  <li><a href="#">Yet another</a></li>
</ul>
        

        <a href="#" class="button" data-dropdown="drop">Zombies</a>
        <ul id="drop" class="[tiny small medium large content]f-dropdown" data-dropdown-content>
          <li><%= link_to 'Agregar', new_zombie_path %></li>
          <li><%= link_to 'Mostrar', zombies_path %></li>
        </ul>
          
          
     


    <%= yield %>
  </body>
</html>

app/views/zombies/_form.html.erb
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="file_field">
    <%= form.file_field :avatar%>
  </div>
<div class="row">
  <div class="large-6 columns">
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :zombie_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :zombie_bio %>
  </div>
  </div>
  <div class="large-6 columns">
  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :zombie_age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :zombie_email %>
  </div>

  <div class="field">
    <%= form.label :rotten %>
    <%= form.check_box :rotten, id: :zombie_rotten %>
  </div>
  </div>
  <div class="actions">
    <%= form.submit class: "button round"%>
  </div>
</div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<div class="Links button"><%= link_to 'Mostrar', @zombie %> </div>
<div class="Links button alert"> <%= link_to 'Atrás', zombies_path %></div>

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>
<div class="row">
<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td class="Avatar"><%= image_tag zombie.avatar %></td>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
        <td><%= zombie.email %></td>
        <td><%= zombie.rotten %></td>
        <td class="button round Links"><%= link_to 'Mostrar', zombie %></td>
        <td class="button round success Links"><%= link_to 'Editar', edit_zombie_path(zombie) %></td>
        <td class="button round alert Links"><%= link_to 'Eliminar', zombie, method: :delete, data: {confirm: '¿Estás seguro?'} %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/zombies/new.html.erb
<h1>Nuevo Zombie</h1>

<%= render 'form', zombie: @zombie %>

<div class="button alert"><%= link_to 'Back', zombies_path %></div>

app/views/zombies/show.html.erb
  
<div class="row Letra">
<div class="large-4 columns">
<div class:"AvatarShow">
  <%= image_tag @zombie.avatar, :width=>300, :height=>300%>
</div>
</div>
</div>
<div class="row">
  <div class="large-6 columns">
<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @zombie.bio %>
</p>
  </div>
  <div class="large-6 columns">
<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @zombie.email %>
</p>

<p>
  <strong>Rotten:</strong>
  <%= @zombie.rotten %>
</p>
  </div>
</div>
<div id="brains">
  <%=render :partial => @zombie.brains.reverse %>
</div>

<%= form_for([@zombie,Brain.new], remote:true) do |f| %>
<div class="field">
  <%= f.label :flavor%>
  <%= f.text_field :flavor%>  
</div>
<div class="field">
  <%= f.label  :iq%>
  <%= f.text_field :iq%>  
</div>
<div class="field">
  <%= f.label  :fresh  %>
  <%= f.check_box :fresh %>  
</div>
<div class="actions">
  <%= f.submit "Agregar" %>  
</div>
<% end %>

<div class: "Links button round"><%= link_to 'Editar', edit_zombie_path(@zombie) %></div> 
<div class: "Links button round"><%= link_to 'Atras', zombies_path %></div>